# Generated by Django 4.1.5 on 2023-01-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
